version: '3.8'

services:
  app:
    image: dog-pics-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/dogs?schema=public  # Updated connection string
      JWT_SECRET: Aditya_GuPtA_123
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: dogs
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"  # Added explicit port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: